#!/bin/bash
# List of projects to migrate
PROJECTS=(
"ArtisDoc"
"ArtisDocNext"
"AutoScribe"
"AutoScrum"
"BotFactory"
"BrowserBot"
"ChatTyper"
"CodeFireman"
"CoderX"
"CryptoScout"
"DriveOrganizer"
"DriverAgent"
"FarmManager"
"FeedSync"
"FintelliView"
"FiremanDev"
"GuanacoBot"
"MailBridge"
"MailGenius"
"MemoryBoost"
"MemoryHub"
"MiniHub"
"MoneyMaker"
"MyWiki"
"NautaChallenge"
"NotebookSync"
"OCRTester"
"OllamaFork"
"OrthoPosture"
"PassOrganizer"
"PassRotate"
"PayBridge"
"PhotoSwipe"
"PostureAnalyze"
"ProjectHub"
"PumpGuard"
"QRGen"
"ResearchBot"
"RulesEngine"
"ScribeBridge"
"ScrumBots"
"SecretsVault"
"ServerOps"
"SideDoc"
"SignalsLab"
"SmartDocs"
"SocialAuto"
"StrategyLab"
"TermOrchestra"
"TradeBook"
"VaultConnect"
"VaultPro"
"WellnessTrack"
"WhatsGuard"
)

echo "Starting Batch Migration of ${#PROJECTS[@]} projects..." >> /home/luis/projects/MIGRATION_LOG.txt

for proj in "${PROJECTS[@]}"; do
  python3 /home/luis/projects/ops-scripts/migrate_project.py "/home/luis/projects/$proj"
done

echo "Batch Migration Completed." >> /home/luis/projects/MIGRATION_LOG.txt
